language: dart
# Speed up builds by using containerization.
sudo: false
dart:
- 2.2.0
with_content_shell: false
dart_task:
- dartanalyzer: --fatal-infos --fatal-warnings ./
- dartfmt
script:
  - pub run test test/hnpwa_client_test.dart
  - pub get --packages-dir
  - pub global activate coverage
  - pub global run coverage:collect_coverage --port=8111 -o coverage.json --resume-isolates --wait-paused &
  - dart --observe=8111 test/hnpwa_client_test.dart
  - nohup pub global run coverage:format_coverage --report-on lib --in coverage.json --out lcov.info --lcov
after_success:
  - bash <(curl -s https://codecov.io/bash)
